In [1]:
print("Hello")

Hello


In [2]:
name=input("enter your name: ")
age=int(input("Enter your age: "))
height=float(input("Enter your height: "))
print("My name is",name,"My age is",age,"My height is",height)



My name is jh My age is 5 My height is 5.2


In [3]:
first_no=int(input("enter ur no."))
second_no=int(input("enter ur no."))
third_no=int(input("enter ur no."))
ave=(first_no+second_no+third_no)//3
print(ave)

94


In [4]:
print(-5%3)

1


In [5]:
age=int(input("enter ur age"))
if age >=18:
    print("can vote")
else:
    print("can not vote")
print("end")

can vote
end


In [6]:
first=int(input("enter ur no"))
second=int(input("enter ur no"))
third=int(input("enter ur no"))
if first==second==third:
    print("equilateral triangle angle")
elif first==second or second ==third or third==first :
    print("isoscelen")
else:
    print("scelene")

isoscelen


In [7]:
i=1
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [8]:
i=1
for i in range(11,0,-1):
    print(i)

11
10
9
8
7
6
5
4
3
2
1


In [9]:
list/numpy

NameError: name 'numpy' is not defined

In [11]:
list=[1,3,5,2,7,5,11,14,12]
a=len(list)//2
print(list[a])

7


In [12]:
list=[1,3,5,2,7,5,11,14,12]
list.reverse()
print(list)

[12, 14, 11, 5, 7, 2, 5, 3, 1]


In [13]:
list=[1,2,3,4,5,3,2,1,3,4]
print(list[-2:-9:-4])

[3, 5]


In [14]:
list=[1,2,3,4,5,3,2,1,3,4]
print(list[-2:-9:2])

[]


In [15]:
list=[1,2,3,4,5,3,2,1,3,4]
print(list[::-2])

[4, 1, 3, 4, 2]


In [16]:
list=[1,2,3,4,5,3,2,1,3,4]
for ele in list:
    print(ele)

1
2
3
4
5
3
2
1
3
4


In [17]:
list=[1,2,3,4,5,3,2,1,3,4]
for i in range (len(list)):
    print(list[i],end=" ")

1 2 3 4 5 3 2 1 3 4 

In [18]:
list=[1,2,3,4,5,3,2,1,3,4]
for i in range (len(list)):
    print(list[i],end="@")

1@2@3@4@5@3@2@1@3@4@

In [19]:
list=[1,2,3,4,5,3,2,1,3,4]
for i in range (len(list)):
    print(list[i],end="~~~~~")

1~~~~~2~~~~~3~~~~~4~~~~~5~~~~~3~~~~~2~~~~~1~~~~~3~~~~~4~~~~~

In [ ]:
# list=[1,2,3,4,5,6,7,8,9,10]
# for i in list:
#     if()
#     print(even)

In [20]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
import numpy as np
s=[0,1,2,3,4]
print(type(s))
a=np.array(s)
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [22]:
# dimension
a.ndim

1

In [23]:
# shape
print(a.shape)

(5,)


In [24]:
s=[[0,1],[2,3]]
print(type(s))
a=np.array(s)
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [25]:
a.ndim

2

In [26]:
list=[0,1,2,3,4,5,6,7,8,9,10,11,12,13]
a=list[::2]
print(a)
print(sum(a))


[0, 2, 4, 6, 8, 10, 12]
42


In [27]:
# list=[0,1,2,3,4,5,6,7,8,9,10,11,12,13]
# print(sum(list))
# if (list%2==0):
#     print (list,"even")
# else:
#     print("odd")

In [28]:
list=[0,1,2,4,7,9,5,8,2,6]
even_sum=0
for i in list:
    if (i%2==0):
        even_sum+=i
print(even_sum)

22


In [14]:
# numbers=[0,1,2,0,7,9,5,0,2,6]
# even_sum=0
# for i in range(0,len(numbers)):
#     if i%2==0:
#         even_sum+=numbers[i]
# print(even_sum)

16


In [ ]:
# numbers=[0,1,2,0,7,9,5,0,2,6]
# i=0
# while (i<=numbers):
#     if i%2==0:
#         sum+=i
#     print(sum)

In [29]:
import numpy as np
a=np.zeros((2,2),dtype="int")
print(a)

[[0 0]
 [0 0]]


In [30]:
import numpy as np
a=np.ones((6,6),dtype="float")
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [31]:
! pip3 install opencv-python

In [1]:
import cv2

In [1]:
! pip install mediapipe

Defaulting to user installation because normal site-packages is not writeable
  Using cached mediapipe-0.10.18-cp39-cp39-win_amd64.whl (50.9 MB)
  Using cached protobuf-4.25.5-cp39-cp39-win_amd64.whl (413 kB)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
  Using cached jaxlib-0.4.30-cp39-cp39-win_amd64.whl (51.9 MB)
  Using cached jax-0.4.30-py3-none-any.whl (2.0 MB)
  Using cached opencv_contrib_python-4.10.0.84-cp37-abi3-win_amd64.whl (45.5 MB)
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
  Using cached sentencepiece-0.2.0-cp39-cp39-win_amd64.whl (991 kB)
     -------------------------------------- 71.9/71.9 kB 360.8 kB/s eta 0:00:00
     ------------------------------------ 211.3/211.3 kB 536.1 kB/s eta 0:00:00


In [ ]:
import cv2 
cap=cv2.VideoCapture(0) 

while True :
    sucess,img=cap.read()
    cv2.imshow("Video",img)
    cv2.waitKey(1)


In [ ]:
import cv2
import mediapipe as mp
import numpy as np
mphand=mp.solutions.hands
hand=mphand.Hands()
mpDraw=mp.solutions.drawing_utils


cap=cv2.VideoCapture(0) 

while True:
    sucess,img=cap.read()
    imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    result=hand.process(imgrgb)
    # print(result.multi_hands_landmarks)
    if result.multi_hand_landmarks:
        for handlm in result.multi_hand_landmarks:
            for id,lm in enumerate(handlm.landmark):
                # print(id,lm)
                h,w,c=img.shape
                cx,cy=int(lm.x*w),int(lm.y*h)
                print(id,cx,cy)
                
            mpDraw.draw_landmarks(img,handlm,mphand.HAND_CONNECTIONS)
            
            
    cv2.imshow("Video",img)
    cv2.waitKey(1)


In [ ]:
# import cv2
# import mediapipe as mp
# import numpy as np
# mphand=mp.solutions.hands
# hand=mphand.Hands(min_tracking_confidence=0.95,min_hand_detection_confidence=0.95)
# mpDraw=mp.solutions.drawing_utils



# cap=cv2.VideoCapture(0) 

# while True:
#     sucess,img=cap.read()
#     imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
#     result=hand.process(imgrgb)
#     # print(result.multi_hands_landmarks)
#     if result.multi_hand_landmarks:
#         for handlm in result.multi_hand_landmarks:
#             mpDraw.draw_landmarks(img,handlm)
            
            
#     cv2.imshow("Video",img)
#     cv2.waitKey(1)

In [ ]:
import cv2
import mediapipe as mp
import numpy as np 
mphand=mp.solutions.hands
hand=mphand.Hands()

mpDraw=mp.solutions.drawing_utils

cap=cv2.VideoCapture(0)

while True:
    sucess,img=cap.read()

    imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    result=hand.process(imgrgb)
   # print(result.multi_hand_landmarks)
    if result.multi_hand_landmarks:
        for handlm in result.multi_hand_landmarks:
                   
            for id,lm in enumerate(handlm.landmark):
                #print(id,lm) 
                h,w,c=img.shape
                cx,cy=int(lm.x*w),int(lm.y*h)
                print(id,cx,cy)

            mpDraw.draw_landmarks(img,handlm,mphand.HAND_CONNECTIONS)
    cv2.imshow("Vedio",img)
    cv2.waitKey(1)

0 151 434
1 158 447
2 172 457
3 184 466
4 193 473
5 184 448
6 201 457
7 212 464
8 220 469
9 184 436
10 201 433
11 212 430
12 218 427
13 183 426
14 198 423
15 204 423
16 207 424
17 179 417
18 192 415
19 197 417
20 199 418
0 83 274
1 100 298
2 108 331
3 102 356
4 90 372
5 116 328
6 105 365
7 93 378
8 86 382
9 105 316
10 92 350
11 78 366
12 69 375
13 90 305
14 77 337
15 65 353
16 57 364
17 73 295
18 60 322
19 51 338
20 44 351
0 87 262
1 71 271
2 64 292
3 66 314
4 64 335
5 97 295
6 94 334
7 86 357
8 78 373
9 115 300
10 111 339
11 100 361
12 89 376
13 124 306
14 123 340
15 112 360
16 100 374
17 128 310
18 128 337
19 120 354
20 110 365
0 109 221
1 94 228
2 88 246
3 90 266
4 89 286
5 126 253
6 124 288
7 117 308
8 110 324
9 139 257
10 136 297
11 125 318
12 114 332
13 144 263
14 143 298
15 131 317
16 120 330
17 144 267
18 144 294
19 136 309
20 127 319
0 98 237
1 83 243
2 81 256
3 83 273
4 85 291
5 116 263
6 120 291
7 114 310
8 108 324
9 130 270
10 133 303
11 122 323
12 111 336
13 135 276
14 140

In [ ]:
#part 1 to create paintwindow
import cv2
import numpy as np
import mediapipe as mp
from collections import deque

# Here is code for Canvas setup
paintWindow = np.zeros((471, 636, 3)) + 255
paintWindow = cv2.rectangle(paintWindow, (40, 1), (140, 65), (0, 0, 0), 2) #black
paintWindow = cv2.rectangle(paintWindow, (160, 1), (255, 65), (255, 0, 0), 2)#blue
paintWindow = cv2.rectangle(paintWindow, (275, 1), (370, 65), (0, 255, 0), 2)# Green
paintWindow = cv2.rectangle(paintWindow, (390, 1), (485, 65), (0, 0, 255), 2) #red
paintWindow = cv2.rectangle(paintWindow, (505, 1), (600, 65), (0, 255, 255), 2)#Yellow


cv2.rectangle(paintWindow, (160, 1), (255, 65), (255, 0, 0), -1)  # blue
cv2.rectangle(paintWindow, (275, 1), (370, 65), (0, 255, 0), -1)  # Green
cv2.rectangle(paintWindow, (390, 1), (485, 65), (0, 0, 255), -1)  #red
cv2.rectangle(paintWindow, (505, 1), (600, 65), (0, 255, 255), -1)  # Yellow

cv2.putText(paintWindow, "CLEAR", (49, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "BLUE", (185, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "GREEN", (298, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "RED", (420, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "YELLOW", (520, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)

cv2.imshow("Paint", paintWindow)

cv2.waitKey(1)

-1

In [ ]:
#part 3 draw color panels on webcam window
import cv2
import mediapipe as mp
import numpy as np 
mphand=mp.solutions.hands
hands=mphand.Hands()

mpDraw=mp.solutions.drawing_utils

cap=cv2.VideoCapture(0)

while True:
        ret, frame = cap.read()
        x, y, c = frame.shape

        
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        
        # insert color panel
        frame = cv2.rectangle(frame, (40, 1), (140, 65), (0, 0, 0), 2)
        frame = cv2.rectangle(frame, (160, 1), (255, 65), (255, 0, 0), 2)
        frame = cv2.rectangle(frame, (275, 1), (370, 65), (0, 255, 0), 2)
        frame = cv2.rectangle(frame, (390, 1), (485, 65), (0, 0, 255), 2) 
        frame = cv2.rectangle(frame, (505, 1), (600, 65), (0, 255, 255), 2)
        cv2.putText(frame, "CLEAR", (49, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
        cv2.putText(frame, "BLUE", (185, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
        cv2.putText(frame, "GREEN", (298, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
        cv2.putText(frame, "RED", (420, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
        cv2.putText(frame, "YELLOW", (520, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)

        
        results = hands.process(frame_rgb)

        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                
                for idx, landmark in enumerate(hand_landmarks.landmark):
                    cx, cy = int(landmark.x * frame.shape[1]), int(landmark.y * frame.shape[0])
                    if idx==4 or idx==8:
                        cv2.circle(frame, (cx, cy), 15, (255, 255, 0), -1)

                
                mp_drawing = mp.solutions.drawing_utils
                mp_drawing.draw_landmarks(frame, hand_landmarks, mphand.HAND_CONNECTIONS)

        
        cv2.imshow('Hand Landmarks', frame)

        
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    
cap.release()
cv2.destroyAllWindows()

c:\Users\atbad\OneDrive\Desktop\Air canvas\.venv\Lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '


KeyboardInterrupt: 

In [ ]:
#part 5 our air canva is ready now we can draw in canva

# Import necessary frameworks
import cv2
import numpy as np
import mediapipe as mp
from collections import deque

# Initialize deques and indices for - blue,green,red,yellow colors
bpoints = [deque(maxlen=1024)]
gpoints = [deque(maxlen=1024)]
rpoints = [deque(maxlen=1024)]
ypoints = [deque(maxlen=1024)]

# These indices will be used to mark the points in particular deque of the specified color
blue_index = 0
green_index = 0
red_index = 0
yellow_index = 0



colors = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (0, 255, 255)]
colorIndex = 0

# Here is code for Canvas setup
paintWindow = np.zeros((471, 636, 3)) + 255
paintWindow = cv2.rectangle(paintWindow, (40, 1), (140, 65), (0, 0, 0), 2)
paintWindow = cv2.rectangle(paintWindow, (160, 1), (255, 65), (255, 0, 0), 2)
paintWindow = cv2.rectangle(paintWindow, (275, 1), (370, 65), (0, 255, 0), 2)
paintWindow = cv2.rectangle(paintWindow, (390, 1), (485, 65), (0, 0, 255), 2)
paintWindow = cv2.rectangle(paintWindow, (505, 1), (600, 65), (0, 255, 255), 2)

cv2.rectangle(paintWindow, (505, 1), (600, 65), (255, 255, 0), -1)
cv2.rectangle(paintWindow, (160, 1), (255, 65), (255, 0, 0), -1)  # Blue
cv2.rectangle(paintWindow, (275, 1), (370, 65), (0, 255, 0), -1)  # Green
cv2.rectangle(paintWindow, (390, 1), (485, 65), (0, 0, 255), -1)  # Red
cv2.rectangle(paintWindow, (505, 1), (600, 65), (0, 255, 255), -1)  # Yellow

cv2.putText(paintWindow, "CLEAR", (49, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "BLUE", (185, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "GREEN", (298, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "RED", (420, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "YELLOW", (520, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)



mpHands = mp.solutions.hands
hands = mpHands.Hands(max_num_hands=1, min_detection_confidence=0.7)
mpDraw = mp.solutions.drawing_utils


cap = cv2.VideoCapture(0)
ret = True
while ret:
    
    ret, frame = cap.read()

    x, y, c = frame.shape

    # Flip the frame vertically
    frame = cv2.flip(frame, 1)
    
    framergb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    frame = cv2.rectangle(frame, (40, 1), (140, 65), (0, 0, 0), 2)
    frame = cv2.rectangle(frame, (160, 1), (255, 65), (255, 0, 0), 2)
    frame = cv2.rectangle(frame, (275, 1), (370, 65), (0, 255, 0), 2)
    frame = cv2.rectangle(frame, (390, 1), (485, 65), (0, 0, 255), 2)
    frame = cv2.rectangle(frame, (505, 1), (600, 65), (0, 255, 255), 2)
    cv2.putText(frame, "CLEAR", (49, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
    cv2.putText(frame, "BLUE", (185, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
    cv2.putText(frame, "GREEN", (298, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
    cv2.putText(frame, "RED", (420, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
    cv2.putText(frame, "YELLOW", (520, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
    

    
    result = hands.process(framergb)

    
    if result.multi_hand_landmarks:
        landmarks = []
        for handslms in result.multi_hand_landmarks:
            for lm in handslms.landmark:
               
                lmx = int(lm.x * 640)
                lmy = int(lm.y * 480)

                landmarks.append([lmx, lmy])

            
            mpDraw.draw_landmarks(frame, handslms, mpHands.HAND_CONNECTIONS)
        fore_finger = (landmarks[8][0], landmarks[8][1])
        center = fore_finger
        thumb = (landmarks[4][0], landmarks[4][1])
        cv2.circle(frame, center, 3, (0, 255, 0), -1)
        print(center[1] - thumb[1])
        if (thumb[1] - center[1] < 30):
            bpoints.append(deque(maxlen=512))
            blue_index += 1
            gpoints.append(deque(maxlen=512))
            green_index += 1
            rpoints.append(deque(maxlen=512))
            red_index += 1
            ypoints.append(deque(maxlen=512))
            yellow_index += 1

        elif center[1] <= 65:
            if 40 <= center[0] <= 140:  # Clear Button
                bpoints = [deque(maxlen=512)]
                gpoints = [deque(maxlen=512)]
                rpoints = [deque(maxlen=512)]
                ypoints = [deque(maxlen=512)]

                blue_index = 0
                green_index = 0
                red_index = 0
                yellow_index = 0

                paintWindow[67:, :, :] = 255
            elif 160 <= center[0] <= 255:
                colorIndex = 0  # Blue
            elif 275 <= center[0] <= 370:
                colorIndex = 1  # Green
            elif 390 <= center[0] <= 485:
                colorIndex = 2  # Red
            elif 505 <= center[0] <= 600:
                colorIndex = 3  # Yellow
        else:
            if colorIndex == 0:
                bpoints[blue_index].appendleft(center)
            elif colorIndex == 1:
                gpoints[green_index].appendleft(center)
            elif colorIndex == 2:
                rpoints[red_index].appendleft(center)
            elif colorIndex == 3:
                ypoints[yellow_index].appendleft(center)
    
    else:
        bpoints.append(deque(maxlen=512))
        blue_index += 1
        gpoints.append(deque(maxlen=512))
        green_index += 1
        rpoints.append(deque(maxlen=512))
        red_index += 1
        ypoints.append(deque(maxlen=512))
        yellow_index += 1

    # Draw lines of all the colors on the canvas and frame
    points = [bpoints, gpoints, rpoints, ypoints]
    #code to draw on canva
    for i in range(len(points)):
        for j in range(len(points[i])):
            for k in range(1, len(points[i][j])):
                if points[i][j][k - 1] is None or points[i][j][k] is None:
                    continue
                cv2.line(frame, points[i][j][k - 1], points[i][j][k], colors[i], 2)
                cv2.line(paintWindow, points[i][j][k - 1], points[i][j][k], colors[i], 2)

    cv2.imshow("Output", frame)
    cv2.imshow("Paint", paintWindow)

    if cv2.waitKey(1) == ord('q'):
        break

# release the webcam and destroy all active windows
cap.release()
cv2.destroyAllWindows()

c:\Users\atbad\OneDrive\Desktop\Air canvas\.venv\Lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '


7
18
1
0
2
-1
0
-18
-26
-58
-67
-65
-63
-53
-52
-51
-52
-54
-69
-69
-77
-73
-56
-48
-49
-38
-40
-66
-63
-61
-60
-53
-51
-52
-61
-61
-63
-59
-51
-51
-53
-54
-56
-58
-58
-52
-52
-43
-44
-44
-28
-27
-8
-7
-3
-2
-3
0
1
-1
-2
1
0
-1
0
0
1
0
0
-2
-1
-1
-2
-1
-1
-1
0
-1
0
-1
0
-1
-1
-1
0
-1
-2
-2
-14
-10
-43
-43
-37
-37
-44
-44
-45
-46
-48
-47
-35
-33
-43
-43
-38
-38
-42
-46
-33
-29
-51
-46
-43
-54
-47
-50
-49
-26
-12
-14
4
-2
-7
-11
-11
-11
-11
-14
-11
-13
-12
-9
-8
-9
-7
-9
-6
-7
-8
-8
-8
-9
-5
-5
-8
-2
-5
-10
-8
-4
-10
-9
-10
-12
-13
-10
-13
-7
-12
-14
-18
-15
-15
-12
-13
-11
-15
-12
-14
-13
-6
-6
-4
-3
-17
-15
-16
-35
-13
-13
-12
-4
-20
-18
-18
-17
14
6
-7
1
-2
-1
-5
-6
-9
-5
-8
-6
-8
-7
-10
-1
-6
-3
-3
-1
-1
1
-1
-2
-3
-7
-6
-8
-7
-7
-7
-6
-3
-7
-8
-6
-6
-7
-11
-9
-11
-14
-14
-13
-12
-14
-13
-13
-13
-13
-12
-6
-7
-9
-7
-9
-12
-9
-10
-15
-12
-12
-10
10
9
-13
-3
-11
-18
-10
-7
-1
-2
1
1
-6
-6
-8
-8
-6
-3
-7
0
0
-4
-1
-4
-3
-4
-2
-1
-2
-4
-6
-6
-8
-7
-7
-8
-7
-8
-7
-11
-6
-7
-7
-7
-6
-9
-8


AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
#part 5 our air canva is ready now we can draw in canva

# Import necessary frameworks
import cv2
import numpy as np
import mediapipe as mp
from collections import deque

# Initialize deques and indices for - blue,green,red,yellow colors
bpoints = [deque(maxlen=1024)]
gpoints = [deque(maxlen=1024)]
rpoints = [deque(maxlen=1024)]
ypoints = [deque(maxlen=1024)]

# These indices will be used to mark the points in particular deque of the specified color
blue_index = 0
green_index = 0
red_index = 0
yellow_index = 0



colors = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (0, 255, 255)]
colorIndex = 0

# Here is code for Canvas setup
paintWindow = np.zeros((471, 636, 3)) + 255
paintWindow = cv2.rectangle(paintWindow, (40, 1), (140, 65), (0, 0, 0), 2)
paintWindow = cv2.rectangle(paintWindow, (160, 1), (255, 65), (255, 0, 0), 2)
paintWindow = cv2.rectangle(paintWindow, (275, 1), (370, 65), (0, 255, 0), 2)
paintWindow = cv2.rectangle(paintWindow, (390, 1), (485, 65), (0, 0, 255), 2)
paintWindow = cv2.rectangle(paintWindow, (505, 1), (600, 65), (0, 255, 255), 2)

cv2.rectangle(paintWindow, (505, 1), (600, 65), (255, 255, 0), -1)
cv2.rectangle(paintWindow, (160, 1), (255, 65), (255, 0, 0), -1)  # Blue
cv2.rectangle(paintWindow, (275, 1), (370, 65), (0, 255, 0), -1)  # Green
cv2.rectangle(paintWindow, (390, 1), (485, 65), (0, 0, 255), -1)  # Red
cv2.rectangle(paintWindow, (505, 1), (600, 65), (0, 255, 255), -1)  # Yellow

cv2.putText(paintWindow, "CLEAR", (49, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "BLUE", (185, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "GREEN", (298, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "RED", (420, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)
cv2.putText(paintWindow, "YELLOW", (520, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2, cv2.LINE_AA)



mpHands = mp.solutions.hands
hands = mpHands.Hands(max_num_hands=1, min_detection_confidence=0.7)
mpDraw = mp.solutions.drawing_utils


cap = cv2.VideoCapture(0)
ret = True
while ret:
    
    ret, frame = cap.read()

    x, y, c = frame.shape

    # Flip the frame vertically
    frame = cv2.flip(frame, 1)
    
    framergb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    frame = cv2.rectangle(frame, (40, 1), (140, 65), (0, 0, 0), 2)
    frame = cv2.rectangle(frame, (160, 1), (255, 65), (255, 0, 0), 2)
    frame = cv2.rectangle(frame, (275, 1), (370, 65), (0, 255, 0), 2)
    frame = cv2.rectangle(frame, (390, 1), (485, 65), (0, 0, 255), 2)
    frame = cv2.rectangle(frame, (505, 1), (600, 65), (0, 255, 255), 2)
    cv2.putText(frame, "CLEAR", (49, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
    cv2.putText(frame, "BLUE", (185, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
    cv2.putText(frame, "GREEN", (298, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
    cv2.putText(frame, "RED", (420, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
    cv2.putText(frame, "YELLOW", (520, 33), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2, cv2.LINE_AA)
    

    
    result = hands.process(framergb)

    
    if result.multi_hand_landmarks:
        landmarks = []
        for handslms in result.multi_hand_landmarks:
            for lm in handslms.landmark:
               
                lmx = int(lm.x * 640)
                lmy = int(lm.y * 480)

                landmarks.append([lmx, lmy])

            
            mpDraw.draw_landmarks(frame, handslms, mpHands.HAND_CONNECTIONS)
        fore_finger = (landmarks[8][0], landmarks[8][1])
        center = fore_finger
        thumb = (landmarks[4][0], landmarks[4][1])
        cv2.circle(frame, center, 3, (0, 255, 0), -1)
        print(center[1] - thumb[1])
        if (thumb[1] - center[1] < 30):
            bpoints.append(deque(maxlen=512))
            blue_index += 1
            gpoints.append(deque(maxlen=512))
            green_index += 1
            rpoints.append(deque(maxlen=512))
            red_index += 1
            ypoints.append(deque(maxlen=512))
            yellow_index += 1

        elif center[1] <= 65:
            if 40 <= center[0] <= 140:  # Clear Button
                bpoints = [deque(maxlen=512)]
                gpoints = [deque(maxlen=512)]
                rpoints = [deque(maxlen=512)]
                ypoints = [deque(maxlen=512)]

                blue_index = 0
                green_index = 0
                red_index = 0
                yellow_index = 0

                paintWindow[67:, :, :] = 255
            elif 160 <= center[0] <= 255:
                colorIndex = 0  # Blue
            elif 275 <= center[0] <= 370:
                colorIndex = 1  # Green
            elif 390 <= center[0] <= 485:
                colorIndex = 2  # Red
            elif 505 <= center[0] <= 600:
                colorIndex = 3  # Yellow
        else:
            if colorIndex == 0:
                bpoints[blue_index].appendleft(center)
            elif colorIndex == 1:
                gpoints[green_index].appendleft(center)
            elif colorIndex == 2:
                rpoints[red_index].appendleft(center)
            elif colorIndex == 3:
                ypoints[yellow_index].appendleft(center)
    
    else:
        bpoints.append(deque(maxlen=512))
        blue_index += 1
        gpoints.append(deque(maxlen=512))
        green_index += 1
        rpoints.append(deque(maxlen=512))
        red_index += 1
        ypoints.append(deque(maxlen=512))
        yellow_index += 1

    # Draw lines of all the colors on the canvas and frame
    points = [bpoints, gpoints, rpoints, ypoints]
    #code to draw on canva
    for i in range(len(points)):
        for j in range(len(points[i])):
            for k in range(1, len(points[i][j])):
                if points[i][j][k - 1] is None or points[i][j][k] is None:
                    continue
                cv2.line(frame, points[i][j][k - 1], points[i][j][k], colors[i], 2)
                cv2.line(paintWindow, points[i][j][k - 1], points[i][j][k], colors[i], 2)

    cv2.imshow("Output", frame)
    cv2.imshow("Paint", paintWindow)

    if cv2.waitKey(1) == ord('q'):
        break

# release the webcam and destroy all active windows
cap.release()
cv2.destroyAllWindows()

12
53
47
32
36
39
44
21
41
33
44
38
45
5
1
1
5
4
8
-1
-5
-7
-7
-8
-8
-7
-12
-24
-27
-25
-24
-22
-20
1
9
7
5
6
11
7
8
11
9
9
13
9
12
7
20
19
18
20
10
13
20
20
19
20
5
24
19
23
18
16
14
12
5
8
5
6
5
8
6
10
7
11
10
10
9
10
7
10
7
9
7
9
8
8
9
6
6
8
9
8
8
8
8
6
4
9
10
11
7
10
8
6
6
11
8
7
5
5
4
6
10
5
8
7
7
6
11
9
8
9
10
12
9
7
25
22
32
37
28
38
37
38
36
29
32
33
32
28
29
34
34
42
40
37
38
39
38
42
38
40
41
40
38
39
38
39
40
40
37
34
36
37
34
39
38
38
37
39
40
38
38
37
35
38
38
39
38
38
37
36
38
38
37
37
36
37
38
36
36
35
37
38
36
40
39
40
36
39
40
41
34
34
34
34
34
36
32
33
37
35
36
34
34
35
37
38
34
32
32
35
35
32
31
29
32
31
30
32
35
35
32
34
34
31
30
32
31
26
28
28
31
33
32
31
31
30
31
28
31
27
27
29
27
29
27
28
27
29
25
31
30
27
27
27
35
36
38
41
41
40
43
46
43
43
49
47
47
46
49
49
45
46
45
39
40
27
29
27
29
32
40
46
50
51
54
21
66
69
61
58
56
59
51
50
40
42
40
39
38
38
34
35
35
35
41
42
39
39
36
36
38
39
41
40
41
40
43
44
43
42
45
46
45
44
44
44
44
45
44
45
43
46
43
44
45
46
43
44
44
